### ISSUE TITLE
Feat: Show number of active users at any time

### ISSUE THREAD

**Issue by bhargav794** [suyalamritanshu/Realtime-Chat-App#10]
Right now we are showing usernames of all the users what I'd like to do is also show the number of active users at any given moment I want to show the number of active users in the place of the red box drawn in below image. If you like this idea please assign this issue to me and I will work on it Thanks in advance.
![Screenshot 2021-10-05 182058](https://user-images.githubusercontent.com/66371186/136026021-0f9fc19a-d0d9-4d63-a429-6b68f67642dc.png)

**Comment by suyalamritanshu** [comment]
Sure, assigning this to you but you have to attach a video with this pr

**Comment by bhargav794** [comment]
thanks
