### ISSUE TITLE
Make the app lighter

### ISSUE THREAD

**Issue by udz-codes** [suyalamritanshu/Realtime-Chat-App#3]
As this project has a package.json file, we don't need to pass node_modules along with the project, and to avoid this, we can add a .gitignore file.

**Comment by udz-codes** [comment]
> As this project has a package.json file, we don't need to pass node_modules along with the project, and to avoid this, we can add a .gitignore file.

I you would like, I can work on this.

**Comment by suyalamritanshu** [comment]
Your suggestion is good but just putting one folder in gitignore does not make a remarkable contribution. You can do this but also do anything else also so that this project UI or the code looks lighter

**Comment by udz-codes** [comment]
> Your suggestion is good but just putting one folder in gitignore does not make a remarkable contribution. You can do this but also do anything else also so that this project UI or the code looks lighter

Yes, I will be raising another issue for that. I just thought this is necessary.

**Comment by suyalamritanshu** [comment]
Cool then this issue is yours. I am assigning this to you
